site_name: xiaomai-bot-docs-cn
site_url: https://docs.ifvlab.com/projects/xiaomai/
site_description: xiaomai-bot documention
site_author: IFVLAB members

repo_url: https://github.com/ifvlaboratory/xiaomai-bot-docs-cn/

nav:
  - 开始: "index.md"
  - 安装: "user-guide/installation.md"
  - 配置: "user-guide/configuration.md"
  - 插件帮助:
      - 内置插件: "modules-help/required/index.md"
      - 运行插件: "modules-help/self_contained/index.md"

theme:
  name: material
  language: zh
  palette:
    - primary: blue
    - accent: blue
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
  locale: zh_CN

extra:
  analytics:
    provider: google
    property: G-H2FJ5C1Q3N

plugins:
  - toc-md:
