site_name: xiaomai-bot-docs-cn
site_url: https://docs.ifvlab.com/projects/xiaomai/
site_description: xiaomai-bot documention
site_author: IFVLAB members

repo_url: https://github.com/ifvlaboratory/xiaomai-bot-docs-cn/

nav:
  - 开始: "index.md"
  - 安装: "user-guide/installation.md"
  - 配置: "user-guide/configuration.md"
  - 插件帮助:
      - 内置插件: "modules-help/required/index.md"
      - 运行插件:
          - BF1战绩: "modules-help/self_contained/bf1_info.md"
          - BF1服管: "modules-help/self_contained/bf1_servermanager.md"

theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-H2FJ5C1Q3N

markdown_extensions:  
  - toc:       
    toc_depth: '2'

plugins:
  - optimize
